### ISSUE TITLE
supervisord missconfiguration with configured username

### ISSUE THREAD

**Issue by chymian** [ai-dock/base-image#1]
hey Rob,
thanks a lot for your images, they are fantasic!

on the linux-desktop (KDE) image:  
supervisord's config files for `syncthing.conf` and `servicportal.conf` have a fixed `user=user` entry which get not changed to the configured username (here: sky) , hence fail to start.

```log
lnxdesk-sky  | useradd: user 'sky' already exists
lnxdesk-sky  | chpasswd: (user user) pam_chauthtok() failed, error:
lnxdesk-sky  | Authentication token manipulation error
lnxdesk-sky  | chpasswd: (line 1, user user) password not changed
lnxdesk-sky  | Error: Invalid user name sky in section 'program:syncthing' (file: '/etc/supervisor/supervisord/conf.d/syncthing.conf')
lnxdesk-sky  | For help, use /usr/bin/supervisord -h
```

### workaround:

attach to the container

```bash

# fix supervisord
# user=user
sed -i s/user=user/user=sky/g /etc/supervisor/supervisord/conf.d/*.conf

# update supervisord
supervisorctl update
```

maybe one has to restart the image.

**Comment by robballantyne** [comment]
Good catch!

I'll fix this in the next build. The user line should read

```
USER=$USER_NAME
```

so that it can be replaced at startup (init.sh line 288). 

Thanks for reporting

**Comment by robballantyne** [comment]
Fixed in recent builds
